//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel2Oracle.BGScreen {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CurveDatas", Namespace="http://schemas.datacontract.org/2004/07/BigScreen.Service", ItemName="Curvedata", KeyName="TagName", ValueName="List")]
    [System.SerializableAttribute()]
    public class CurveDatas : System.Collections.Generic.Dictionary<string, Excel2Oracle.BGScreen.Data[]> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagNameData", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TagNameData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BGScreen.IBusinessService")]
    public interface IBusinessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/Test", ReplyAction="http://tempuri.org/IBusinessService/TestResponse")]
        System.IO.Stream Test(string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/GetCurveValues", ReplyAction="http://tempuri.org/IBusinessService/GetCurveValuesResponse")]
        Excel2Oracle.BGScreen.CurveDatas GetCurveValues(string tagNames, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectMethod", ReplyAction="http://tempuri.org/IBusinessService/DoSelectMethodResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.CurveDatas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.Data[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.TagNameData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.TagNameData))]
        object[][] DoSelectMethod(string selectSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectMethodRetTable", ReplyAction="http://tempuri.org/IBusinessService/DoSelectMethodRetTableResponse")]
        System.IO.Stream DoSelectMethodRetTable(string selectSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectMethod2", ReplyAction="http://tempuri.org/IBusinessService/DoSelectMethod2Response")]
        System.IO.Stream DoSelectMethod2(string selectSql, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/GetTagValuesWithJsonEx", ReplyAction="http://tempuri.org/IBusinessService/GetTagValuesWithJsonExResponse")]
        Excel2Oracle.BGScreen.TagNameData[] GetTagValuesWithJsonEx(string tagNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/OperateSql", ReplyAction="http://tempuri.org/IBusinessService/OperateSqlResponse")]
        int OperateSql(string Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectMethodWithHeader", ReplyAction="http://tempuri.org/IBusinessService/DoSelectMethodWithHeaderResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.CurveDatas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.Data[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.TagNameData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.TagNameData))]
        object[][] DoSelectMethodWithHeader(string selectSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/GetPeriodHisValues", ReplyAction="http://tempuri.org/IBusinessService/GetPeriodHisValuesResponse")]
        Excel2Oracle.BGScreen.CurveDatas GetPeriodHisValues(string tagNames, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectSqlByKey", ReplyAction="http://tempuri.org/IBusinessService/DoSelectSqlByKeyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.CurveDatas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.Data[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.TagNameData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Excel2Oracle.BGScreen.TagNameData))]
        object[][] DoSelectSqlByKey(string key, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectSqlByKey2", ReplyAction="http://tempuri.org/IBusinessService/DoSelectSqlByKey2Response")]
        System.IO.Stream DoSelectSqlByKey2(string key, string param, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/GetTagValuesWithJsonEx2", ReplyAction="http://tempuri.org/IBusinessService/GetTagValuesWithJsonEx2Response")]
        System.IO.Stream GetTagValuesWithJsonEx2(string tagNames, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/MakeXLSFile", ReplyAction="http://tempuri.org/IBusinessService/MakeXLSFileResponse")]
        System.IO.Stream MakeXLSFile(string path, string fileName, string tableInnerHTML, string modelHtmlName, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoSelectMethodByParams", ReplyAction="http://tempuri.org/IBusinessService/DoSelectMethodByParamsResponse")]
        System.IO.Stream DoSelectMethodByParams(string selectCols, string tableName, string innerTables, string condition, string vagueCondition, string inCondition, string orderDesc, string orderAsc, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoDeleteMethodByParams", ReplyAction="http://tempuri.org/IBusinessService/DoDeleteMethodByParamsResponse")]
        System.IO.Stream DoDeleteMethodByParams(string tableName, string condition, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoUpdateMethodByParams", ReplyAction="http://tempuri.org/IBusinessService/DoUpdateMethodByParamsResponse")]
        System.IO.Stream DoUpdateMethodByParams(string tableName, string condition, string updateValue, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoAddMethodByParams", ReplyAction="http://tempuri.org/IBusinessService/DoAddMethodByParamsResponse")]
        System.IO.Stream DoAddMethodByParams(string keyCol, string tableName, string defaultsCols, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/DoAddNormalByParams", ReplyAction="http://tempuri.org/IBusinessService/DoAddNormalByParamsResponse")]
        System.IO.Stream DoAddNormalByParams(string tableName, string values, string callback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/GetSISXML", ReplyAction="http://tempuri.org/IBusinessService/GetSISXMLResponse")]
        System.IO.Stream GetSISXML(string callback, string programNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessServiceChannel : Excel2Oracle.BGScreen.IBusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<Excel2Oracle.BGScreen.IBusinessService>, Excel2Oracle.BGScreen.IBusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream Test(string callback) {
            return base.Channel.Test(callback);
        }
        
        public Excel2Oracle.BGScreen.CurveDatas GetCurveValues(string tagNames, System.DateTime start, System.DateTime end) {
            return base.Channel.GetCurveValues(tagNames, start, end);
        }
        
        public object[][] DoSelectMethod(string selectSql) {
            return base.Channel.DoSelectMethod(selectSql);
        }
        
        public System.IO.Stream DoSelectMethodRetTable(string selectSql) {
            return base.Channel.DoSelectMethodRetTable(selectSql);
        }
        
        public System.IO.Stream DoSelectMethod2(string selectSql, string callback) {
            return base.Channel.DoSelectMethod2(selectSql, callback);
        }
        
        public Excel2Oracle.BGScreen.TagNameData[] GetTagValuesWithJsonEx(string tagNames) {
            return base.Channel.GetTagValuesWithJsonEx(tagNames);
        }
        
        public int OperateSql(string Sql) {
            return base.Channel.OperateSql(Sql);
        }
        
        public object[][] DoSelectMethodWithHeader(string selectSql) {
            return base.Channel.DoSelectMethodWithHeader(selectSql);
        }
        
        public Excel2Oracle.BGScreen.CurveDatas GetPeriodHisValues(string tagNames, System.DateTime start, System.DateTime end) {
            return base.Channel.GetPeriodHisValues(tagNames, start, end);
        }
        
        public object[][] DoSelectSqlByKey(string key, string param) {
            return base.Channel.DoSelectSqlByKey(key, param);
        }
        
        public System.IO.Stream DoSelectSqlByKey2(string key, string param, string callback) {
            return base.Channel.DoSelectSqlByKey2(key, param, callback);
        }
        
        public System.IO.Stream GetTagValuesWithJsonEx2(string tagNames, string callback) {
            return base.Channel.GetTagValuesWithJsonEx2(tagNames, callback);
        }
        
        public System.IO.Stream MakeXLSFile(string path, string fileName, string tableInnerHTML, string modelHtmlName, string callback) {
            return base.Channel.MakeXLSFile(path, fileName, tableInnerHTML, modelHtmlName, callback);
        }
        
        public System.IO.Stream DoSelectMethodByParams(string selectCols, string tableName, string innerTables, string condition, string vagueCondition, string inCondition, string orderDesc, string orderAsc, string callback) {
            return base.Channel.DoSelectMethodByParams(selectCols, tableName, innerTables, condition, vagueCondition, inCondition, orderDesc, orderAsc, callback);
        }
        
        public System.IO.Stream DoDeleteMethodByParams(string tableName, string condition, string callback) {
            return base.Channel.DoDeleteMethodByParams(tableName, condition, callback);
        }
        
        public System.IO.Stream DoUpdateMethodByParams(string tableName, string condition, string updateValue, string callback) {
            return base.Channel.DoUpdateMethodByParams(tableName, condition, updateValue, callback);
        }
        
        public System.IO.Stream DoAddMethodByParams(string keyCol, string tableName, string defaultsCols, string callback) {
            return base.Channel.DoAddMethodByParams(keyCol, tableName, defaultsCols, callback);
        }
        
        public System.IO.Stream DoAddNormalByParams(string tableName, string values, string callback) {
            return base.Channel.DoAddNormalByParams(tableName, values, callback);
        }
        
        public System.IO.Stream GetSISXML(string callback, string programNo) {
            return base.Channel.GetSISXML(callback, programNo);
        }
    }
}
